from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setup_ui(self, main_window):
        # region setup
        main_window.setObjectName("main_window")
        main_window.resize(413, 670)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.le_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_1.setGeometry(QtCore.QRect(10, 0, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.le_1.setFont(font)
        self.le_1.setReadOnly(True)
        self.le_1.setObjectName("le_1")
        self.le_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_2.setGeometry(QtCore.QRect(10, 60, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.le_2.setFont(font)
        self.le_2.setReadOnly(True)
        self.le_2.setObjectName("le_2")
        self.bt_ac = QtWidgets.QPushButton(self.centralwidget)
        self.bt_ac.setGeometry(QtCore.QRect(10, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_ac.setFont(font)
        self.bt_ac.setObjectName("bt_ac")
        self.bt_del = QtWidgets.QPushButton(self.centralwidget)
        self.bt_del.setGeometry(QtCore.QRect(110, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_del.setFont(font)
        self.bt_del.setObjectName("bt_del")
        self.bt_percent = QtWidgets.QPushButton(self.centralwidget)
        self.bt_percent.setGeometry(QtCore.QRect(210, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_percent.setFont(font)
        self.bt_percent.setObjectName("bt_percent")
        self.bt_divide = QtWidgets.QPushButton(self.centralwidget)
        self.bt_divide.setGeometry(QtCore.QRect(310, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_divide.setFont(font)
        self.bt_divide.setObjectName("bt_divide")
        self.bt_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_7.setGeometry(QtCore.QRect(10, 230, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_7.setFont(font)
        self.bt_7.setObjectName("bt_7")
        self.bt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_4.setGeometry(QtCore.QRect(10, 330, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_4.setFont(font)
        self.bt_4.setObjectName("bt_4")
        self.bt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_1.setGeometry(QtCore.QRect(10, 430, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_1.setFont(font)
        self.bt_1.setObjectName("bt_1")
        self.bt_0 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_0.setGeometry(QtCore.QRect(10, 530, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_0.setFont(font)
        self.bt_0.setObjectName("bt_0")
        self.bt_point = QtWidgets.QPushButton(self.centralwidget)
        self.bt_point.setGeometry(QtCore.QRect(110, 530, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_point.setFont(font)
        self.bt_point.setObjectName("bt_point")
        self.bt_equal = QtWidgets.QPushButton(self.centralwidget)
        self.bt_equal.setGeometry(QtCore.QRect(210, 530, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_equal.setFont(font)
        self.bt_equal.setObjectName("bt_equal")
        self.bt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_2.setGeometry(QtCore.QRect(110, 430, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_2.setFont(font)
        self.bt_2.setObjectName("bt_2")
        self.bt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_3.setGeometry(QtCore.QRect(210, 430, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_3.setFont(font)
        self.bt_3.setObjectName("bt_3")
        self.bt_plus = QtWidgets.QPushButton(self.centralwidget)
        self.bt_plus.setGeometry(QtCore.QRect(310, 430, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_plus.setFont(font)
        self.bt_plus.setObjectName("bt_plus")
        self.bt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_5.setGeometry(QtCore.QRect(110, 330, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_5.setFont(font)
        self.bt_5.setObjectName("bt_5")
        self.bt_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_8.setGeometry(QtCore.QRect(110, 230, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_8.setFont(font)
        self.bt_8.setObjectName("bt_8")
        self.bt_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_6.setGeometry(QtCore.QRect(210, 330, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_6.setFont(font)
        self.bt_6.setObjectName("bt_6")
        self.bt_min = QtWidgets.QPushButton(self.centralwidget)
        self.bt_min.setGeometry(QtCore.QRect(310, 330, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_min.setFont(font)
        self.bt_min.setObjectName("bt_min")
        self.bt_9 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_9.setGeometry(QtCore.QRect(210, 230, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_9.setFont(font)
        self.bt_9.setObjectName("bt_9")
        self.bt_fold = QtWidgets.QPushButton(self.centralwidget)
        self.bt_fold.setGeometry(QtCore.QRect(310, 230, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt_fold.setFont(font)
        self.bt_fold.setObjectName("bt_fold")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 413, 22))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        # endregion

        self.bt_ac.clicked.connect(self.clear_all)
        self.bt_del.clicked.connect(self.delete)

        # region num click event
        self.bt_0.clicked.connect(lambda: self.press_num(self.bt_0.text()))
        self.bt_1.clicked.connect(lambda: self.press_num(self.bt_1.text()))
        self.bt_2.clicked.connect(lambda: self.press_num(self.bt_2.text()))
        self.bt_3.clicked.connect(lambda: self.press_num(self.bt_3.text()))
        self.bt_4.clicked.connect(lambda: self.press_num(self.bt_4.text()))
        self.bt_5.clicked.connect(lambda: self.press_num(self.bt_5.text()))
        self.bt_6.clicked.connect(lambda: self.press_num(self.bt_6.text()))
        self.bt_7.clicked.connect(lambda: self.press_num(self.bt_7.text()))
        self.bt_8.clicked.connect(lambda: self.press_num(self.bt_8.text()))
        self.bt_9.clicked.connect(lambda: self.press_num(self.bt_9.text()))
        # endregion

        self.bt_plus.clicked.connect(lambda: self.press_act(self.bt_plus.text()))
        self.bt_min.clicked.connect(lambda: self.press_act(self.bt_min.text()))
        self.bt_fold.clicked.connect(lambda: self.press_act(self.bt_fold.text()))
        self.bt_point.clicked.connect(lambda: self.press_act(self.bt_point.text()))
        self.bt_divide.clicked.connect(lambda: self.press_act(self.bt_divide.text()))
        self.bt_percent.clicked.connect(lambda: self.press_act(self.bt_percent.text()))

        self.bt_equal.clicked.connect(self.press_equal)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Simple Calculator"))
        self.bt_ac.setText(_translate("main_window", "AC"))
        self.bt_del.setText(_translate("main_window", "Del"))
        self.bt_del.setShortcut(_translate("main_window", "Backspace"))
        self.bt_plus.setText(_translate("main_window", "+"))
        self.bt_plus.setShortcut(_translate("main_window", "+"))
        self.bt_min.setText(_translate("main_window", "-"))
        self.bt_min.setShortcut(_translate("main_window", "-"))
        self.bt_fold.setText(_translate("main_window", "*"))
        self.bt_fold.setShortcut(_translate("main_window", "*"))
        self.bt_divide.setText(_translate("main_window", "/"))
        self.bt_divide.setShortcut(_translate("main_window", "/"))
        self.bt_equal.setText(_translate("main_window", "="))
        self.bt_equal.setShortcut(_translate("main_window", "Return"))

        self.bt_percent.setText(_translate("main_window", "%"))
        self.bt_point.setText(_translate("main_window", "."))

        self.bt_0.setText(_translate("main_window", "0"))
        self.bt_0.setShortcut(_translate("main_window", "0"))
        self.bt_1.setText(_translate("main_window", "1"))
        self.bt_1.setShortcut(_translate("main_window", "1"))
        self.bt_2.setText(_translate("main_window", "2"))
        self.bt_2.setShortcut(_translate("main_window", "2"))
        self.bt_3.setText(_translate("main_window", "3"))
        self.bt_3.setShortcut(_translate("main_window", "3"))
        self.bt_4.setText(_translate("main_window", "4"))
        self.bt_4.setShortcut(_translate("main_window", "4"))
        self.bt_5.setText(_translate("main_window", "5"))
        self.bt_5.setShortcut(_translate("main_window", "5"))
        self.bt_6.setText(_translate("main_window", "6"))
        self.bt_6.setShortcut(_translate("main_window", "6"))
        self.bt_7.setText(_translate("main_window", "7"))
        self.bt_7.setShortcut(_translate("main_window", "7"))
        self.bt_8.setText(_translate("main_window", "8"))
        self.bt_8.setShortcut(_translate("main_window", "8"))
        self.bt_9.setText(_translate("main_window", "9"))
        self.bt_9.setShortcut(_translate("main_window", "9"))

    def press_num(self, isi):
        if self.le_2.text() == "0":
            self.le_2.setText(self.le_2.text()[:-1])
        self.le_2.setText(self.le_2.text() + str(isi))

    def press_act(self, isi):
        cur = self.le_2.text()
        if cur != "" and cur != "-" and cur[-1] != isi:
            if cur[-1] == "+" or cur[-1] == "-" or cur[-1] == "*" or cur[-1] == "/":
                if isi != "-":
                    self.le_2.setText(cur[:-1])
                    cur = self.le_2.text()
            if isi == ".":
                if "." in cur:
                    isi = ""
            self.le_2.setText(cur + str(isi))
        elif cur == "" and isi == "-":
            self.le_2.setText(str(isi))

    def press_equal(self):
        self.le_1.setText(self.le_2.text())
        h = self.le_2.text().replace("%", "/100")
        hasil = eval(h)
        isi = str(hasil) if (hasil % 1) != 0 else str(int(hasil))
        self.le_2.setText(isi)

    def clear_all(self):
        if self.le_2.text() == "":
            self.le_1.setText("")
        self.le_2.setText("")

    def delete(self):
        isi = self.le_2.text()
        if isi != "":
            self.le_2.setText(isi[:-1])


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    my_main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setup_ui(my_main_window)
    my_main_window.show()
    sys.exit(app.exec_())
